"""create medications medication_schedules reminder_logs

Revision ID: 87e9723e56da
Revises: 9b0060b00005
Create Date: 2026-07-12 12:53:16.315654

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "87e9723e56da"
down_revision: str | Sequence[str] | None = "9b0060b00005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("strength", sa.String(length=100), nullable=True),
        sa.Column("dosage_instruction", sa.String(length=500), nullable=False),
        sa.Column("simplified_instruction", sa.String(length=500), nullable=True),
        sa.Column("purpose_simplified", sa.String(length=500), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medications_user_id"), "medications", ["user_id"], unique=False)
    op.create_table(
        "medication_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("time_of_day", sa.Time(), nullable=False),
        sa.Column("frequency_type", sa.String(length=20), nullable=False),
        sa.Column("days_of_week", sa.String(length=20), nullable=True),
        sa.Column("meal_relation", sa.String(length=20), nullable=False),
        sa.Column("dose_amount", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["medication_id"], ["medications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_schedules_medication_id"),
        "medication_schedules",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_schedules_user_id"), "medication_schedules", ["user_id"], unique=False
    )
    op.create_table(
        "reminder_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["medication_id"], ["medications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_logs_medication_id"), "reminder_logs", ["medication_id"], unique=False
    )
    op.create_index(op.f("ix_reminder_logs_user_id"), "reminder_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminder_logs_user_id"), table_name="reminder_logs")
    op.drop_index(op.f("ix_reminder_logs_medication_id"), table_name="reminder_logs")
    op.drop_table("reminder_logs")
    op.drop_index(op.f("ix_medication_schedules_user_id"), table_name="medication_schedules")
    op.drop_index(op.f("ix_medication_schedules_medication_id"), table_name="medication_schedules")
    op.drop_table("medication_schedules")
    op.drop_index(op.f("ix_medications_user_id"), table_name="medications")
    op.drop_table("medications")
    # ### end Alembic commands ###
